apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-dao
spec:
  replicas: 2
  selector:
    matchLabels:
      
      si3mshady: eks-dao
    
  template:
    metadata:
      labels:
        
        si3mshady: eks-dao
    spec:
      containers:
      - name: dao-eks
        image: si3mshady/eks-dao-ec2     
        ports:
        - containerPort: 80
          hostPort: 80

--- 
apiVersion: v1
kind: Service
metadata: 
  name: dao-eks

spec: 
  ports: 
    - port: 80
      targetPort: 80     
    
  selector: 
    si3mshady: eks-dao
  type: LoadBalancer